[project]
name = "test-project"
version = "0.0.1"
requires-python = ">=3.13,<4.0"

dependencies = ["python-dotenv", "requests"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
